{"name": "反向用例: raise TypeError", "status": "passed", "attachments": [{"name": "log", "source": "e6d93e80-bbe1-4f2e-ab11-6a10b183e080-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "[1, 2]"}, {"name": "error_type", "value": "'TypeError'"}], "start": 1624194308155, "stop": 1624194308155, "uuid": "b797ae1f-9a45-40ea-ba79-8a8db468f424", "historyId": "07925969ec676fc6cd03bb705509bfe0", "testCaseId": "1b5aab2181c21923f6bd8223ee598e23", "fullName": "Test_2021_06_17.test_cal.test_cal.TestAddDivision#test_add_fail", "labels": [{"name": "story", "value": "测试加法"}, {"name": "feature", "value": "测试计算器"}, {"name": "parentSuite", "value": "Test_2021_06_17.test_cal"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestAddDivision"}, {"name": "host", "value": "192.168.8.102"}, {"name": "thread", "value": "56258-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_2021_06_17.test_cal.test_cal"}]}